### ISSUE TITLE
GL11Util

### ISSUE THREAD

**Issue by xss1de** [sendQueue/ClickGui#2]
Hi, you forgot the GL11Util file. If it's not difficult, can you please add?
![image](https://user-images.githubusercontent.com/44199277/113468784-24379a00-946a-11eb-9d86-b34f878bb421.png)

**Comment by xss1de** [comment]
more precisely, there is no entire folder of managment

**Comment by sendQueue** [comment]
as described in Panel.java "Some renderstuff requires https://github.com/sendQueue/LWJGLUtil" :)
if you have trouble adding it your self, you may add me on discord Vinii#9482
